"""Meeting minutes generator in Fed format."""

from pathlib import Path

from fed_board.config import Settings, get_settings
from fed_board.models.meeting import MeetingResult


class MinutesGenerator:
    """Generates FOMC meeting minutes in official format."""

    def __init__(self, settings: Settings | None = None) -> None:
        """
        Initialize the minutes generator.

        Args:
            settings: Application settings
        """
        self.settings = settings or get_settings()

    def generate_markdown(self, result: MeetingResult) -> str:
        """
        Generate meeting minutes in Markdown format.

        Args:
            result: The meeting result to generate minutes for

        Returns:
            Markdown string
        """
        meeting = result.meeting
        decision = result.decision

        # Build the vote tally
        vote_list = self._format_vote_list(result)
        dissent_section = self._format_dissent_section(result)

        markdown = f"""# Minutes of the Federal Open Market Committee

## {meeting.display_date}

A joint meeting of the Federal Open Market Committee and the Board of Governors of the Federal Reserve System was held in the offices of the Board of Governors on {meeting.display_date}.

---

## Developments in Financial Markets and Open Market Operations

The manager of the System Open Market Account reported on developments in domestic and foreign financial markets during the period since the Committee met previously. Financial conditions remained broadly stable, with market participants attentive to incoming economic data and Federal Reserve communications.

Treasury yields {self._describe_yield_movement(result)} as markets adjusted expectations for the path of monetary policy. The S&P 500 index {self._describe_equity_movement(result)} over the intermeeting period.

---

## Staff Review of the Economic Situation

{result.economic_outlook}

### Inflation

The staff's assessment indicated that inflation remained {self._describe_inflation_status(result)} percent on a 12-month basis. Core inflation, which excludes food and energy prices, continued to run above the Committee's 2 percent longer-run objective.

### Labor Market

Labor market conditions remained {self._describe_labor_market(result)}. The unemployment rate held near historically low levels, while payroll gains continued at a solid pace. Wage growth remained elevated but showed signs of gradual moderation.

### Economic Activity

Real GDP growth continued at a moderate pace. Consumer spending remained resilient, supported by a strong labor market and household balance sheets. Business fixed investment showed mixed signals, with equipment spending softening while structures investment held steady.

---

## Staff Economic Outlook

The staff's projection for the U.S. economy continued to anticipate a period of below-trend growth followed by a gradual return to trend. The projection incorporated the assumption that financial conditions would remain generally supportive of growth.

The staff continued to judge that the risks to the baseline projection for real activity were tilted to the downside, while the risks to the inflation projection were tilted to the upside. The possibility that inflation could prove more persistent than expected remained a key concern.

---

## Participants' Views on Current Conditions and the Economic Outlook

In their discussion of current conditions and the economic outlook, participants noted that recent indicators suggested that economic activity had been expanding at a solid pace.

{result.participants_discussion}

### Assessment of Inflation

Participants generally agreed that inflation remained elevated relative to the Committee's 2 percent objective. {self._generate_inflation_discussion(result)}

### Labor Market Conditions

Participants observed that the labor market remained tight, with demand for workers still exceeding available supply in many sectors. {self._generate_labor_discussion(result)}

### Policy Considerations

{self._generate_policy_discussion(result)}

---

## Committee Policy Action

{result.statement_summary}

{vote_list}

{dissent_section}

---

## Voting

Voting for this action: {self._get_for_voters(result)}

{self._get_dissent_voters(result)}

---

*Minutes prepared by the staff of the Federal Open Market Committee*

---

**DISCLAIMER: AI-GENERATED SIMULATION**

This document was generated by an AI simulation system and does not represent actual Federal Reserve decisions or policy. The content is for educational and research purposes only.

**Model Used:** {result.model_used}

**Generated:** {result.created_at.strftime('%Y-%m-%d %H:%M:%S')}

*Fed Decision Board - AI-powered FOMC meeting simulator*
"""
        return markdown

    def _format_vote_list(self, result: MeetingResult) -> str:
        """Format the vote tally."""
        decision = result.decision
        if decision.rate_change_bps > 0:
            action = f"raise the target range by {decision.rate_change_bps} basis points"
        elif decision.rate_change_bps < 0:
            action = f"lower the target range by {abs(decision.rate_change_bps)} basis points"
        else:
            action = "maintain the target range"

        return f"""The Committee decided to {action}, establishing the target range for the federal funds rate at {decision.rate_range_str}."""

    def _format_dissent_section(self, result: MeetingResult) -> str:
        """Format the dissent analysis section."""
        if not result.has_dissents:
            return ""

        sections = ["### Dissenting Views\n"]
        for analysis in result.dissent_analyses:
            sections.append(
                f"**{analysis.dissenter_name}** voted against the action, preferring "
                f"{analysis.dissenter_preference}. {analysis.reasoning}\n"
            )
        return "\n".join(sections)

    def _get_for_voters(self, result: MeetingResult) -> str:
        """Get list of members who voted for the decision."""
        voters = [v.member_name for v in result.votes if v.vote_for_decision]
        return ", ".join(voters)

    def _get_dissent_voters(self, result: MeetingResult) -> str:
        """Get dissent information."""
        dissenters = [v for v in result.votes if v.is_dissent]
        if not dissenters:
            return ""

        lines = ["\nVoting against this action:"]
        for vote in dissenters:
            lines.append(f"- {vote.member_name} (preferred {vote.preferred_rate:.2f}%)")
        return "\n".join(lines)

    def _describe_yield_movement(self, result: MeetingResult) -> str:
        """Describe treasury yield movements."""
        impact = result.market_impact
        if impact is None:
            return "remained relatively stable"
        if impact.treasury_10y_change_bps > 5:
            return "increased"
        elif impact.treasury_10y_change_bps < -5:
            return "decreased"
        return "remained relatively stable"

    def _describe_equity_movement(self, result: MeetingResult) -> str:
        """Describe equity market movements."""
        impact = result.market_impact
        if impact is None:
            return "remained relatively stable"
        if impact.sp500_change_pct > 1:
            return "advanced"
        elif impact.sp500_change_pct < -1:
            return "declined"
        return "remained relatively stable"

    def _describe_inflation_status(self, result: MeetingResult) -> str:
        """Describe inflation status."""
        return "elevated"  # Simplified - would ideally use actual data

    def _describe_labor_market(self, result: MeetingResult) -> str:
        """Describe labor market conditions."""
        return "tight but gradually normalizing"

    def _generate_inflation_discussion(self, result: MeetingResult) -> str:
        """Generate inflation discussion based on vote preferences."""
        hawk_count = sum(1 for v in result.vote_preferences if "inflation" in v.reasoning.lower())
        if hawk_count > len(result.vote_preferences) / 2:
            return "Several participants expressed concern about the persistence of inflation and stressed the importance of bringing it back to target in a timely manner."
        return "While inflation remained elevated, several participants noted progress in recent months and expressed cautious optimism about the disinflation process."

    def _generate_labor_discussion(self, result: MeetingResult) -> str:
        """Generate labor market discussion."""
        return "Some participants noted that labor market conditions, while still tight, had shown signs of coming into better balance between supply and demand."

    def _generate_policy_discussion(self, result: MeetingResult) -> str:
        """Generate policy discussion based on the decision."""
        decision = result.decision
        if decision.rate_change_bps > 0:
            return "In their consideration of policy, participants generally agreed that the stance of monetary policy remained restrictive and that further increases in the target range were warranted to bring inflation back to 2 percent."
        elif decision.rate_change_bps < 0:
            return "In their consideration of policy, participants generally agreed that with inflation continuing to moderate and the risks becoming more balanced, it was appropriate to begin the process of normalizing the stance of monetary policy."
        return "In their consideration of policy, participants generally agreed that the current stance of monetary policy remained appropriate given the economic outlook and the balance of risks."

    def save_markdown(
        self,
        result: MeetingResult,
        output_dir: Path | None = None,
    ) -> Path:
        """
        Save minutes as Markdown file.

        Args:
            result: Meeting result to generate minutes for
            output_dir: Output directory (defaults to settings minutes_dir)

        Returns:
            Path to the saved file
        """
        if output_dir is None:
            output_dir = self.settings.minutes_dir
        output_dir.mkdir(parents=True, exist_ok=True)

        markdown = self.generate_markdown(result)
        filename = f"{result.meeting.month_str}.md"
        filepath = output_dir / filename

        with open(filepath, "w") as f:
            f.write(markdown)

        return filepath
