"""Meeting minutes generator in official Fed format."""

from pathlib import Path

from fed_board.agents.personas import FOMC_MEMBERS, get_voting_members
from fed_board.config import Settings, get_settings
from fed_board.models.meeting import MeetingResult
from fed_board.models.member import Role


class MinutesGenerator:
    """Generates FOMC meeting minutes in official format."""

    def __init__(self, settings: Settings | None = None) -> None:
        """
        Initialize the minutes generator.

        Args:
            settings: Application settings
        """
        self.settings = settings or get_settings()

    def generate_markdown(self, result: MeetingResult) -> str:
        """
        Generate meeting minutes in Markdown format matching Fed official style.

        Args:
            result: The meeting result to generate minutes for

        Returns:
            Markdown string in official Fed minutes format
        """
        meeting = result.meeting
        decision = result.decision
        year = meeting.meeting_date.year

        # Build the opening paragraph
        opening = self._build_opening_paragraph(meeting)

        # Build sections
        financial_markets = self._build_financial_markets_section(result)
        staff_economic = self._build_staff_economic_section(result)
        staff_financial = self._build_staff_financial_section(result)
        staff_outlook = self._build_staff_outlook_section(result)
        participants_views = self._build_participants_views_section(result)
        policy_actions = self._build_policy_actions_section(result)
        voting_section = self._build_voting_section(result)
        attendance_section = self._build_attendance_section(year)

        markdown = f"""# Minutes of the Federal Open Market Committee
## {meeting.display_date}

{opening}

## Developments in Financial Markets and Open Market Operations

{financial_markets}

## Staff Review of the Economic Situation

{staff_economic}

## Staff Review of the Financial Situation

{staff_financial}

## Staff Economic Outlook

{staff_outlook}

## Participants' Views on Current Conditions and the Economic Outlook

{participants_views}

## Committee Policy Actions

{policy_actions}

{voting_section}

---

{attendance_section}

---

_______________________

Secretary of the Federal Open Market Committee

---

**AI-GENERATED SIMULATION NOTICE**

This document was generated by an AI simulation system (Fed Decision Board) using {result.model_used} and does not represent actual Federal Reserve decisions, policy, or official communications. The content is produced for educational, research, and analytical purposes only. Any resemblance to actual FOMC deliberations is simulated based on publicly available information about member positions and economic conditions.

*Generated: {result.created_at.strftime('%B %d, %Y at %H:%M:%S')}*
"""
        return markdown

    def _build_opening_paragraph(self, meeting) -> str:
        """Build the official opening paragraph."""
        if meeting.meeting_end_date:
            start_date = meeting.meeting_date.strftime("%A, %B %d, %Y")
            end_date = meeting.meeting_end_date.strftime("%A, %B %d, %Y")
            return (
                f"A joint meeting of the Federal Open Market Committee and the Board of "
                f"Governors of the Federal Reserve System was held in the offices of the "
                f"Board of Governors on {start_date}, at 10:00 a.m. and continued on "
                f"{end_date}, at 9:00 a.m.¹"
            )
        else:
            date_str = meeting.meeting_date.strftime("%A, %B %d, %Y")
            return (
                f"A joint meeting of the Federal Open Market Committee and the Board of "
                f"Governors of the Federal Reserve System was held in the offices of the "
                f"Board of Governors on {date_str}, at 10:00 a.m.¹"
            )

    def _build_financial_markets_section(self, result: MeetingResult) -> str:
        """Build the financial markets and open market operations section."""
        impact = result.market_impact

        # Describe treasury movements
        if impact:
            if impact.treasury_10y_change_bps > 5:
                treasury_desc = "increased modestly"
            elif impact.treasury_10y_change_bps < -5:
                treasury_desc = "declined"
            else:
                treasury_desc = "were little changed, on net,"

            if impact.sp500_change_pct > 1:
                equity_desc = "advanced"
            elif impact.sp500_change_pct < -1:
                equity_desc = "declined"
            else:
                equity_desc = "were little changed, on net,"
        else:
            treasury_desc = "remained within recent ranges"
            equity_desc = "were little changed, on net,"

        return f"""The manager turned first to an overview of broad market developments during the intermeeting period. Market participants continued to interpret incoming economic data as consistent with a resilient economy. Investors' expectations for the path of the policy rate were attentive to evolving economic conditions and Federal Reserve communications.

The manager turned next to developments in Treasury markets. Treasury yields {treasury_desc} over the intermeeting period. Market-based measures of inflation compensation showed modest movements, reflecting market participants' assessments of the inflation outlook and monetary policy expectations.

Broad equity price indexes {equity_desc} over the intermeeting period. Equity prices showed sensitivity to economic data releases and policymaker communications. Corporate credit spreads remained at relatively tight levels, suggesting continued investor confidence in corporate credit quality.

Regarding international developments, the trade-weighted dollar index showed modest movements over the intermeeting period. Foreign central bank policy expectations continued to evolve in response to global economic conditions.

By unanimous vote, the Committee ratified the Desk's domestic transactions over the intermeeting period. There were no intervention operations in foreign currencies for the System's account during the intermeeting period."""

    def _build_staff_economic_section(self, result: MeetingResult) -> str:
        """Build the staff review of economic situation section."""
        outlook_text = result.economic_outlook if result.economic_outlook else ""

        paragraphs = []

        paragraphs.append(
            "The information available at the time of the meeting indicated that "
            "economic activity had continued to expand. Labor market conditions remained "
            "solid, with payroll gains continuing and the unemployment rate staying at "
            "historically low levels. Consumer price inflation remained above the "
            "Committee's 2 percent longer-run objective."
        )

        if outlook_text:
            paragraphs.append(outlook_text)

        paragraphs.append(
            "The unemployment rate remained at low levels by historical standards. "
            "The pace of payroll employment gains continued at a solid rate. Other "
            "available labor market indicators—such as initial claims for unemployment "
            "insurance benefits, rates of job openings and layoffs, and survey measures "
            "of labor market conditions—were consistent with a labor market that remained "
            "tight but was gradually coming into better balance."
        )

        paragraphs.append(
            "Total consumer price inflation—as measured by the 12-month change in the "
            "price index for personal consumption expenditures (PCE)—remained above the "
            "Committee's 2 percent objective. Core PCE price inflation, which excludes "
            "changes in consumer energy prices and many consumer food prices, also "
            "remained elevated relative to the Committee's goal."
        )

        return "\n\n".join(paragraphs)

    def _build_staff_financial_section(self, result: MeetingResult) -> str:
        """Build the staff review of financial situation section."""
        return """Over the intermeeting period, nominal Treasury yields showed modest movements as market participants assessed incoming economic data and implications for monetary policy. Changes in nominal yields reflected movements in both real yields and inflation compensation.

In domestic credit markets, conditions remained generally supportive for businesses and households. Financing conditions were somewhat restrictive for some borrowers, particularly in sectors sensitive to interest rates. Large businesses continued to access credit markets at a solid pace.

Credit performance remained stable in most markets. Delinquency rates for consumer loans remained elevated in some categories but showed signs of stabilization. Commercial real estate credit conditions continued to warrant close monitoring given the ongoing adjustments in that sector.

Bank lending standards remained somewhat tight across most loan categories, while loan demand showed mixed signals. Market-based financing remained available for investment-grade borrowers at favorable terms."""

    def _build_staff_outlook_section(self, result: MeetingResult) -> str:
        """Build the staff economic outlook section."""
        return """The staff projection for the U.S. economy anticipated continued moderate growth in real GDP. The projection incorporated the assumption that financial conditions would remain generally supportive of economic expansion while monetary policy worked to bring inflation back to the Committee's 2 percent objective.

The staff's inflation forecast anticipated a gradual return toward the Committee's 2 percent longer-run objective, although the path was expected to be uneven. Core inflation was projected to moderate as supply and demand conditions continued to come into better balance.

The staff continued to judge that uncertainty around the baseline projection remained elevated. Risks around the forecast for real activity were seen as roughly balanced. Risks around the inflation forecast remained tilted to the upside, given the possibility that inflation could prove more persistent than expected."""

    def _build_participants_views_section(self, result: MeetingResult) -> str:
        """Build the participants' views section in impersonal Fed style."""
        decision = result.decision

        # Analyze vote preferences to determine sentiment distribution
        hawk_count = sum(
            1 for v in result.vote_preferences
            if v.preferred_rate_change > 0 or "inflation" in v.reasoning.lower()
        )
        dove_count = sum(
            1 for v in result.vote_preferences
            if v.preferred_rate_change < 0 or "employment" in v.reasoning.lower()
        )

        paragraphs = []

        # Opening observation - economic activity
        paragraphs.append(
            "In their discussion of current conditions and the economic outlook, "
            "participants noted that recent indicators suggested that economic activity "
            "had continued to expand at a solid pace. Several participants observed that "
            "consumer spending remained resilient, supported by solid labor income growth "
            "and household balance sheets. A few participants noted that business fixed "
            "investment had shown mixed signals, with strength in some sectors offset by "
            "weakness in others."
        )

        # Inflation discussion - varies based on hawk/dove balance
        if hawk_count > dove_count:
            inflation_text = (
                "Participants observed that inflation remained above the Committee's "
                "2 percent objective. Most participants noted concerns about the persistence "
                "of elevated inflation and emphasized the importance of returning inflation "
                "to the Committee's goal in a timely manner. Several participants observed "
                "that while headline inflation had moderated somewhat, core inflation "
                "remained elevated, particularly in services categories. A few participants "
                "noted that the pace of disinflation had slowed in recent months."
            )
        elif dove_count > hawk_count:
            inflation_text = (
                "Participants observed that inflation remained somewhat above the "
                "Committee's 2 percent objective but had continued to moderate. Several "
                "participants noted that the disinflation process was proceeding broadly "
                "as expected, with goods prices declining and services inflation gradually "
                "easing. A few participants observed that longer-term inflation expectations "
                "remained well anchored, which supported the view that inflation would "
                "continue to move toward the Committee's goal."
            )
        else:
            inflation_text = (
                "Participants observed that inflation remained above the Committee's "
                "2 percent objective. Most participants noted that while inflation had "
                "moved down from its peak, the pace of disinflation had been uneven. "
                "Several participants emphasized the importance of remaining vigilant "
                "about inflation risks, while others noted that progress toward the "
                "inflation objective was continuing."
            )
        paragraphs.append(inflation_text)

        # Labor market discussion
        paragraphs.append(
            "With regard to the labor market, participants observed that conditions "
            "remained solid. Several participants noted that labor demand and supply "
            "had continued to come into better balance, as evidenced by a moderation "
            "in job openings and a gradual uptick in the unemployment rate from very "
            "low levels. Participants generally agreed that the labor market remained "
            "strong by historical standards but was no longer contributing to "
            "inflationary pressures to the same degree as in the past."
        )

        # Economic outlook and risks
        paragraphs.append(
            "In discussing the outlook, participants generally expected that, with "
            "an appropriate stance of monetary policy, inflation would continue to move "
            "toward the Committee's 2 percent objective while the labor market remained "
            "solid. Participants noted that uncertainty about the economic outlook "
            "remained elevated. Several participants emphasized that risks to the outlook "
            "were roughly balanced, while a few participants judged that downside risks "
            "to employment had increased or that upside risks to inflation remained."
        )

        # Policy discussion based on decision
        if decision.rate_change_bps > 0:
            policy_text = (
                "In their consideration of monetary policy at this meeting, "
                "participants judged that it would be appropriate to raise the target "
                "range for the federal funds rate. Most participants agreed that "
                "elevated inflation warranted a continued restrictive stance of "
                "monetary policy. Several participants noted that the Committee "
                "should remain prepared to adjust policy as needed based on incoming "
                "data. A few participants expressed the view that the Committee should "
                "be attentive to the risk of tightening too much."
            )
        elif decision.rate_change_bps < 0:
            policy_text = (
                "In their consideration of monetary policy at this meeting, "
                "participants agreed that inflation had made progress toward the "
                "Committee's 2 percent objective and that risks to achieving the "
                "Committee's employment and inflation goals had moved into better "
                "balance. Most participants supported lowering the target range for "
                "the federal funds rate at this meeting. Several participants noted "
                "that a reduction in policy restraint was appropriate given the "
                "progress on inflation and the current level of rates. A few "
                "participants expressed the view that the Committee should proceed "
                "cautiously in reducing policy restraint."
            )
        else:
            policy_text = (
                "In their consideration of monetary policy at this meeting, "
                "participants generally agreed that the current stance of monetary "
                "policy remained appropriate. Most participants noted that it would "
                "be prudent to maintain the current level of the federal funds rate "
                "while continuing to assess incoming data. Several participants "
                "emphasized that the Committee should remain data dependent and "
                "prepared to adjust policy as warranted. A few participants noted "
                "the importance of clearly communicating the Committee's reaction "
                "function to the public."
            )
        paragraphs.append(policy_text)

        return "\n\n".join(paragraphs)

    def _build_policy_actions_section(self, result: MeetingResult) -> str:
        """Build the committee policy actions section."""
        decision = result.decision
        statement = result.statement_summary if result.statement_summary else ""

        # Determine the action description
        if decision.rate_change_bps > 0:
            action_desc = f"raise the target range for the federal funds rate by {decision.rate_change_bps} basis points"
        elif decision.rate_change_bps < 0:
            action_desc = f"lower the target range for the federal funds rate by {abs(decision.rate_change_bps)} basis points"
        else:
            action_desc = "maintain the target range for the federal funds rate"

        paragraphs = []

        paragraphs.append(
            "In their discussions of monetary policy for this meeting, members "
            "agreed that economic activity had continued to expand. They also agreed "
            "that job gains had remained solid and that the unemployment rate had "
            "stayed at low levels. Members observed that inflation remained above "
            "the Committee's 2 percent longer-run goal."
        )

        paragraphs.append(
            f"Members agreed that the Committee remained strongly committed to "
            f"returning inflation to its 2 percent objective while supporting maximum "
            f"employment. In support of these goals, members agreed to {action_desc}, "
            f"to {decision.rate_range_str}."
        )

        if statement:
            paragraphs.append(statement)

        paragraphs.append(
            "Members agreed that, in assessing the appropriate stance of monetary "
            "policy, the Committee would continue to monitor the implications of "
            "incoming information for the economic outlook. The Committee would be "
            "prepared to adjust the stance of monetary policy as appropriate if "
            "risks emerged that could impede the attainment of the Committee's goals."
        )

        return "\n\n".join(paragraphs)

    def _build_voting_section(self, result: MeetingResult) -> str:
        """Build the voting section with member names."""
        decision = result.decision

        # Get voters for and against
        for_voters = [v.member_name for v in result.votes if v.vote_for_decision]
        against_voters = [v for v in result.votes if not v.vote_for_decision]

        lines = []
        if for_voters:
            lines.append(f"**Voting for this action:** {'; '.join(for_voters)}.")
        else:
            lines.append("**Voting for this action:** None.")

        if against_voters:
            against_names = []
            for v in against_voters:
                if v.preferred_rate > decision.new_rate_upper:
                    reason = "who preferred to raise rates further"
                elif v.preferred_rate < decision.new_rate_lower:
                    reason = "who preferred a larger rate reduction"
                else:
                    reason = "who preferred a different policy action"
                against_names.append(f"{v.member_name}, {reason}")

            lines.append(f"\n**Voting against this action:** {'; '.join(against_names)}.")
        else:
            lines.append("\n**Voting against this action:** None.")

        return "\n".join(lines)

    def _build_attendance_section(self, year: int) -> str:
        """Build the attendance section listing all participants."""
        # Separate members by role
        chair = None
        vice_chair = None
        vice_chair_supervision = None
        governors = []
        ny_president = None
        voting_presidents = []
        non_voting_presidents = []

        for member in FOMC_MEMBERS:
            if member.role == Role.CHAIR:
                chair = member
            elif member.role == Role.VICE_CHAIR:
                vice_chair = member
            elif member.role == Role.VICE_CHAIR_SUPERVISION:
                vice_chair_supervision = member
            elif member.role == Role.GOVERNOR:
                governors.append(member)
            elif member.role == Role.PRESIDENT:
                if "New York" in member.bank:
                    ny_president = member
                elif member.is_voting_in_year(year):
                    voting_presidents.append(member)
                else:
                    non_voting_presidents.append(member)

        lines = ["## Attendance", ""]

        # Chair and Vice Chairs
        if chair:
            lines.append(f"{chair.name}, Chair")
        if vice_chair:
            lines.append(f"{vice_chair.name}, Vice Chair")
        if vice_chair_supervision:
            lines.append(f"{vice_chair_supervision.name}, Vice Chair for Supervision")

        # Governors
        if governors:
            gov_names = ", ".join([g.name for g in governors])
            lines.append(f"{gov_names}, Governors")

        lines.append("")

        # NY Fed President
        if ny_president:
            lines.append(f"{ny_president.name}, President, Federal Reserve Bank of New York")

        # Voting Reserve Bank Presidents
        if voting_presidents:
            lines.append("")
            lines.append("*Voting Reserve Bank Presidents:*")
            for pres in voting_presidents:
                bank_name = pres.bank.replace("Federal Reserve Bank of ", "")
                lines.append(f"{pres.name}, President, {bank_name}")

        # Non-voting Reserve Bank Presidents
        if non_voting_presidents:
            lines.append("")
            lines.append("*Alternate Members of the Committee:*")
            alt_names = ", ".join([p.name for p in non_voting_presidents[:4]])
            lines.append(alt_names)

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "¹ This AI simulation represents a hypothetical FOMC meeting based on the "
            "economic conditions and member characteristics as of the simulation date. "
            "Attendance reflects the current FOMC composition."
        )

        return "\n".join(lines)

    def save_markdown(
        self,
        result: MeetingResult,
        output_dir: Path | None = None,
    ) -> Path:
        """
        Save minutes as Markdown file.

        Args:
            result: Meeting result to generate minutes for
            output_dir: Output directory (defaults to settings minutes_dir)

        Returns:
            Path to the saved file
        """
        if output_dir is None:
            output_dir = self.settings.minutes_dir
        output_dir.mkdir(parents=True, exist_ok=True)

        markdown = self.generate_markdown(result)
        filename = f"{result.meeting.month_str}.md"
        filepath = output_dir / filename

        with open(filepath, "w") as f:
            f.write(markdown)

        return filepath
